language: cpp
os: linux
before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install cmake3 mpich2 libpetsc-complex-3.7.7 doxygen ; fi
before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_C_COMPILER=`which mpicc` -DCMAKE_CXX_COMPILER=`which mpicxx` -DCMAKE_Fortran_COMPILER=`which mpif90` ..
script: make && make test
