language: cpp
os: linux
before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
install:
    sudo apt-get update -qq
    sudo apt-get install -y cmake3 mpich petsc-dev
before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_C_COMPILER=`which mpicc` -DCMAKE_CXX_COMPILER=`which mpicxx` -DCMAKE_Fortran_COMPILER=`which mpif90` ..
script: make && make test
