language: cpp
os: linux
before_install:
  - test -n $CC
  - test -n $CXX
  - test -n $FC
  - chmod +x install-$TRAVIS_OS_NAME-deps.sh
install: ./install-$TRAVIS_OS_NAME-deps.sh
env:
  - BUILD_TYPE=Debug PETSC_DIR=$PWD/petsc PETSC_ARCH=petsc_debug
  - BUILD_TYPE=Release PETSC_DIR=$PWD/petsc PETSC_ARCH=petsc_opt
script:
  - mkdir build && cd build
  - export TMPDIR=/tmp
  - cmake -DCMAKE_C_COMPILER=`which mpicc` -DCMAKE_CXX_COMPILER=`which mpicxx` -DCMAKE_Fortran_COMPILER='which mpif90' ..
  - make && make test
