language: cpp
os: linux
sudo: false
before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
  - chmod +x install-$TRAVIS_OS_NAME-deps.sh
install: ./install-$TRAVIS_OS_NAME-deps.sh
env:
  - BUILD_TYPE=Debug PETSC_DIR=$PWD/petsc PETSC_ARCH=petsc_debug
  - BUILD_TYPE=Release PETSC_DIR=$PWD/petsc PETSC_ARCH=petsc_opt
script:
  - mkdir build && cd build
  - ls $PWD
  - ls $PETSC_DIR
  - ls $PETSC_DIR/$PETSC_ARCH
  - ls $PETSC_DIR/$PETSC_ARCH/lib
  - export TMPDIR=/tmp
  - ln -s $PETSC_DIR/lib/petsc/conf $PETSC_DIR/conf
  - ln -s $PETSC_DIR/include/petsc/finclude $PETSC_DIR/include/finclude
  - cmake -DCMAKE_C_COMPILER=`which mpicc` -DCMAKE_CXX_COMPILER=`which mpicxx` -DENABLE_UNIT_TESTS=yes ..
  - make && travis_wait 30 make test
