language: cpp
os: linux
before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install cmake3 mpich2 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo pip install petsc ; fi
before_script:
  - mkdir build
  - cd build
  - cmake -DENABLE_UNIT_TESTS=yes ..
script: make && make test
